# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create deployment directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S mkdir -p /var/www/bexa/data/www/8exa.me/bns-neo/field-boss-timer/
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S chown -R ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_USERNAME }} /var/www/bexa/data/www/8exa.me/bns-neo/field-boss-timer/
          debug: true
          use_insecure_cipher: true

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "dist/*"
          target: "/var/www/bexa/data/www/8exa.me/bns-neo/field-boss-timer/"
          strip_components: 1
          debug: true
          use_insecure_cipher: true

      - name: Update nginx config
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S ln -sf /var/www/bexa/data/www/8exa.me/bns-neo/field-boss-timer/nginx.conf /etc/nginx/sites-available/field-boss-timer.8exa.me
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S ln -sf /etc/nginx/sites-available/field-boss-timer.8exa.me /etc/nginx/sites-enabled/
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S nginx -t
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S systemctl restart nginx
          debug: true
          use_insecure_cipher: true
