name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create deployment directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            sudo mkdir -p /var/www/bns-timer
            sudo chown -R ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_USERNAME }} /var/www/bns-timer
          debug: true
          use_insecure_cipher: true

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "dist/*"
          target: "/var/www/bns-timer"
          strip_components: 1
          debug: true
          use_insecure_cipher: true

      - name: Update nginx config
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            sudo ln -sf /var/www/bns-timer/nginx.conf /etc/nginx/sites-available/bns-timer
            sudo ln -sf /etc/nginx/sites-available/bns-timer /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
          debug: true
          use_insecure_cipher: true
